name: Linter

on:
  push:
    branches: [main, release]
  pull_request:
    branches: [main, release]

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
      - name: Run prettier
        run: npm run prettier:check
      - name: Run linter
        run: npm run lint
